# Generated by Django 5.0.6 on 2024-06-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
