# Generated by Django 5.0.6 on 2024-06-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0005_parent_alter_learner_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learner',
        ),
    ]
