# Generated by Django 5.0.6 on 2024-06-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0006_auto_20240605_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_name', models.CharField(max_length=255)),
                ('learner_surname', models.CharField(max_length=255)),
                ('learner_cell_phone_number', models.CharField(max_length=15)),
                ('grade', models.CharField(max_length=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_system.parent')),
            ],
        ),
    ]
