# Generated by Django 5.0.6 on 2024-06-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0007_learner'),
    ]

    operations = [
         migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
