# Generated by Django 5.0.6 on 2024-06-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0009_initial'),
    ]

    operations = [
    ]
