# Generated by Django 5.0.6 on 2024-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0010_auto_20240605_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='parent',
            field=models.CharField(max_length=5),
        ),
    ]
