# Generated by Django 5.0.6 on 2024-06-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0011_alter_learner_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=5)),
                ('bus_route', models.IntegerField()),
                ('pickup_number', models.CharField(max_length=5)),
                ('dropoff_number', models.CharField(max_length=5)),
                ('pickup_name', models.CharField(max_length=15)),
                ('dropoff_name', models.CharField(max_length=15)),
                ('pickup_time', models.CharField(max_length=10)),
                ('dropoff_time', models.CharField(max_length=10)),
                ('waiting_list_number', models.IntegerField(blank=True, null=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('parent_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BusOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=5)),
                ('bus_route', models.IntegerField()),
                ('pickup_number', models.CharField(max_length=5)),
                ('dropoff_number', models.CharField(max_length=5)),
                ('pickup_name', models.CharField(max_length=15)),
                ('dropoff_name', models.CharField(max_length=15)),
                ('pickup_time', models.CharField(max_length=10)),
                ('dropoff_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=5)),
                ('bus_route', models.IntegerField()),
                ('pickup_number', models.CharField(max_length=5)),
                ('dropoff_number', models.CharField(max_length=5)),
                ('pickup_name', models.CharField(max_length=15)),
                ('dropoff_name', models.CharField(max_length=15)),
                ('pickup_time', models.CharField(max_length=10)),
                ('dropoff_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=5)),
                ('bus_route', models.IntegerField()),
                ('pickup_number', models.CharField(max_length=5)),
                ('dropoff_number', models.CharField(max_length=5)),
                ('pickup_name', models.CharField(max_length=15)),
                ('dropoff_name', models.CharField(max_length=15)),
                ('pickup_time', models.CharField(max_length=10)),
                ('dropoff_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='learner_id',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
