# Generated by Django 5.0.6 on 2024-06-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0012_applications_busone_busthree_bustwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='application_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Waiting List', 'Waiting List'), ('Successful', 'Successful')], default='Applied', max_length=20),
        ),
    ]
