# Generated by Django 5.0.6 on 2024-06-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cell',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
